apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
  - protocol: TCP
    port: 80         # External port
    targetPort: 8080 # Forward traffic to port 8080 in the container
