apiVersion: v1
kind: Service
metadata:
  name: canary-whoami-service
spec:
  type: LoadBalancer
  selector:
    app: canary-whoami  
  ports:
  - protocol: TCP
    port: 8081         
    targetPort: 80     
