name: Deploy to EKS

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 

    - name: Set up kubectl
      run: |
        aws eks --region us-east-1 update-kubeconfig --name Tim-TT-EKS-Cluster

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f manifests/deployment.yaml
        kubectl apply -f manifests/service.yaml
        kubectl apply -f manifests/canary-deployment.yaml
        kubectl apply -f manifests/canary-service.yaml

    - name: Verify Deployment and Service
      run: |
        echo "Checking the deployment replicas and image version"
        kubectl get deployment whoami-deployment -o=jsonpath='{.spec.replicas}' 
        kubectl get deployment whoami-deployment -o=jsonpath='{.spec.template.spec.containers[0].image}' 
        echo "Checking the service type"
        kubectl get service whoami-service -o=jsonpath='{.spec.type}'